package com.cfe.cfetime.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmployeeTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeTypeAllPropertiesEquals(EmployeeType expected, EmployeeType actual) {
        assertEmployeeTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertEmployeeTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeTypeAllUpdatablePropertiesEquals(EmployeeType expected, EmployeeType actual) {
        assertEmployeeTypeUpdatableFieldsEquals(expected, actual);
        assertEmployeeTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeTypeAutoGeneratedPropertiesEquals(EmployeeType expected, EmployeeType actual) {
        assertThat(expected)
            .as("Verify EmployeeType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeTypeUpdatableFieldsEquals(EmployeeType expected, EmployeeType actual) {
        assertThat(expected)
            .as("Verify EmployeeType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeTypeUpdatableRelationshipsEquals(EmployeeType expected, EmployeeType actual) {}
}
