package com.cfe.cfetime.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StatusTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusTypeAllPropertiesEquals(StatusType expected, StatusType actual) {
        assertStatusTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertStatusTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusTypeAllUpdatablePropertiesEquals(StatusType expected, StatusType actual) {
        assertStatusTypeUpdatableFieldsEquals(expected, actual);
        assertStatusTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusTypeAutoGeneratedPropertiesEquals(StatusType expected, StatusType actual) {
        assertThat(expected)
            .as("Verify StatusType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusTypeUpdatableFieldsEquals(StatusType expected, StatusType actual) {
        assertThat(expected)
            .as("Verify StatusType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusTypeUpdatableRelationshipsEquals(StatusType expected, StatusType actual) {}
}
