package com.cfe.cfetime.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusAllPropertiesEquals(Status expected, Status actual) {
        assertStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusAllUpdatablePropertiesEquals(Status expected, Status actual) {
        assertStatusUpdatableFieldsEquals(expected, actual);
        assertStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusAutoGeneratedPropertiesEquals(Status expected, Status actual) {
        assertThat(expected)
            .as("Verify Status auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusUpdatableFieldsEquals(Status expected, Status actual) {
        assertThat(expected)
            .as("Verify Status relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusUpdatableRelationshipsEquals(Status expected, Status actual) {
        assertThat(expected)
            .as("Verify Status relationships")
            .satisfies(e -> assertThat(e.getStatusType()).as("check statusType").isEqualTo(actual.getStatusType()));
    }
}
